-- 서울에 위치한 식당 목록 출력하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131118

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(B.SCORE, 2)
FROM REST_INFO A LEFT JOIN (
    SELECT AVG(REVIEW_SCORE) SCORE, REST_ID
    FROM REST_REVIEW B
    GROUP BY REST_ID
) B
ON A.REST_ID = B.REST_ID
WHERE SUBSTR(ADDRESS, 1, 2) = '서울' AND B.SCORE IS NOT NULL
ORDER BY SCORE DESC, FAVORITES DESC
