-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
AND CAR_ID IN 
(SELECT CAR_ID 
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
 GROUP BY CAR_ID 
 HAVING COUNT(CAR_ID) >= 5)
GROUP BY CAR_ID, MONTH(START_DATE)
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC
