-- 물고기 종류 별 대어 찾기
-- https://school.programmers.co.kr/learn/courses/30/lessons/293261

SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM
(SELECT A.ID, A.FISH_TYPE, A.LENGTH, B.MAX_LENGTH
FROM FISH_INFO A JOIN
(SELECT FISH_TYPE, MAX(LENGTH) MAX_LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE) B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = B.MAX_LENGTH) A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
