-- 연도별 대장균 크기의 편차 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/299310

SELECT B.YEAR, B.MAX_SIZE-A.SIZE_OF_COLONY YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN
(SELECT MAX(SIZE_OF_COLONY) MAX_SIZE, YEAR(DIFFERENTIATION_DATE) YEAR FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV
