-- 멸종위기의 대장균 찾기
-- https://school.programmers.co.kr/learn/courses/30/lessons/301651

WITH RECURSIVE TMP AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT C.ID, C.PARENT_ID, TMP.GENERATION + 1
    FROM TMP INNER JOIN ECOLI_DATA AS C
    ON TMP.ID = C.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM TMP
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM TMP
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION