-- 특정 세대의 대장균 찾기
-- https://school.programmers.co.kr/learn/courses/30/lessons/301650

SELECT B.ID
FROM(
    SELECT A.PARENT_ID, A.ID, B.ID AS CHILD_ID
    FROM ECOLI_DATA AS A LEFT JOIN ECOLI_DATA AS B
    ON A.ID = B.PARENT_ID
) AS A LEFT JOIN ECOLI_DATA AS B
ON A.CHILD_ID = B.PARENT_ID
WHERE A.PARENT_ID IS NULL AND B.ID IS NOT NULL